---
# tasks file for vector
- name: update
  become: true
  become_method: su
  ansible.builtin.apt:
    name: '*'
    state: latest
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_{{ family_deb }}.deb"
    dest: "./vector-{{ vector_version }}.deb"
- name: Install vector packages
  become: true
  become_method: su
  ansible.builtin.apt:
    deb: vector-{{ vector_version }}.deb
- name: Replace vector.yaml
  become: true
  become_method: su
  template:
    src: templates/vector.yaml
    dest: /etc/vector/vector.yaml
