---
clickhouse_version: "23.5.2.7"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

# Desired version of vector
vector_version: "0.30.0"
# Path to vector configs
vectore_config_dir: "{{ ansible_user_dir }}/vector_config"
# Vector config dir
vectore_config:
