---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 89.169.173.160
      ansible_private_key_file: ~/.ssh/id_ed25519

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 89.169.142.190
      ansible_private_key_file: ~/.ssh/id_ed25519
