services:
  prometheus:
    user: root:1
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/conf:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=200h
    restart: always
    ports:
      - 9090:9090
  grafana:
    user: root:1
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana
    restart: always
    ports:
      - 3000:3000

  node-exporter:
    user: root:1
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
    - 9100
    ports:
    - 9100:9100
